// <auto-generated />
using System;
using FestivalProject.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FestivalProject.DAL.Migrations
{
    [DbContext(typeof(FestivalDbContext))]
    [Migration("20201109215045_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FestivalProject.DAL.Entities.FestivalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Festivals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46abef51-c53f-4cc5-a270-a2756ef1455e"),
                            Capacity = 1500,
                            City = "Piestany",
                            Country = "Slovakia",
                            Description = "One of the best festivals in Slovakia!",
                            EndTime = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 0,
                            Name = "Grape",
                            Price = 55m,
                            StartTime = new DateTime(2020, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Letiskova 123"
                        });
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.FestivalInterpretEntity", b =>
                {
                    b.Property<Guid>("InterpretId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InterpretId", "FestivalId");

                    b.HasIndex("FestivalId");

                    b.ToTable("FestivalInterprets");

                    b.HasData(
                        new
                        {
                            InterpretId = new Guid("0c41b222-d06b-4021-9668-a4f845bbe57b"),
                            FestivalId = new Guid("46abef51-c53f-4cc5-a270-a2756ef1455e"),
                            Id = new Guid("5da19889-e894-40ad-8033-85d634027e3a")
                        });
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.InterpretEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("LogoUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Interprets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c41b222-d06b-4021-9668-a4f845bbe57b"),
                            Description = "One of the most talented slovak singer.",
                            Genre = 0,
                            LogoUri = "https://www.adamdurica.com/wp-content/uploads/2019/04/album_adam_durica_mandolina-400x400.jpg",
                            Name = "Adam Durica",
                            Rating = 8.7f
                        },
                        new
                        {
                            Id = new Guid("c993e8d3-719b-43d7-908b-e26dc6f4ace0"),
                            Description = "Without word one of the best metal groups.",
                            Genre = 2,
                            LogoUri = "https://www.adamdurica.com/wp-content/uploads/2019/04/album_adam_durica_mandolina-400x400.jpg",
                            Name = "Metallica",
                            Rating = 9.7f
                        });
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.LoginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2347ca2-4a12-46f6-9013-3596b07c63ed"),
                            Password = "123",
                            UserId = new Guid("1ae18ad6-9809-4b19-be41-94aa4ff622f8"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("f7e5a131-c097-47fc-8900-65c51819ecee"),
                            Password = "12345",
                            UserId = new Guid("e3681bb8-1e7f-4e4f-8abe-58dbd211d6d1"),
                            Username = "trdielko"
                        });
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.MemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InterpretEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InterpretId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterpretEntityId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d01d66d9-ac9d-4419-81b3-bc8ae2dfae96"),
                            InterpretId = new Guid("0c41b222-d06b-4021-9668-a4f845bbe57b"),
                            Name = "Janko",
                            Surname = "Mrkvicka"
                        },
                        new
                        {
                            Id = new Guid("af1e3d1f-fbd7-4d2f-a7f1-f7cda8e3547f"),
                            InterpretId = new Guid("0c41b222-d06b-4021-9668-a4f845bbe57b"),
                            Name = "Misko",
                            Surname = "Maly"
                        });
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.ReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Tickets")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8edf6ecd-8d1d-4fbf-92c1-9640e4bc21d9"),
                            Description = "rezervacia sa vybavuje",
                            FestivalId = new Guid("46abef51-c53f-4cc5-a270-a2756ef1455e"),
                            Name = "Grape rezervacia (mozno bude lepsie nejake cislo rezervacie)",
                            Price = 55m,
                            State = 0,
                            Tickets = 1,
                            UserId = new Guid("e3681bb8-1e7f-4e4f-8abe-58dbd211d6d1")
                        });
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.StageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("FestivalEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FestivalEntityId");

                    b.ToTable("Stages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb22c323-729d-49e6-834a-644d47d3dc4c"),
                            Capacity = 600,
                            FestivalId = new Guid("46abef51-c53f-4cc5-a270-a2756ef1455e"),
                            Name = "Main Stage"
                        });
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.StageInterpretEntity", b =>
                {
                    b.Property<Guid>("InterpretId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("ConcertLength")
                        .HasColumnType("time");

                    b.Property<DateTime>("ConcertStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InterpretId", "StageId");

                    b.HasIndex("StageId");

                    b.ToTable("StageInterprets");

                    b.HasData(
                        new
                        {
                            InterpretId = new Guid("0c41b222-d06b-4021-9668-a4f845bbe57b"),
                            StageId = new Guid("cb22c323-729d-49e6-834a-644d47d3dc4c"),
                            ConcertLength = new TimeSpan(0, 2, 30, 0, 0),
                            ConcertStart = new DateTime(2020, 7, 25, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("579ed9de-3b43-494e-98e2-102bf7609447")
                        },
                        new
                        {
                            InterpretId = new Guid("c993e8d3-719b-43d7-908b-e26dc6f4ace0"),
                            StageId = new Guid("cb22c323-729d-49e6-834a-644d47d3dc4c"),
                            ConcertLength = new TimeSpan(0, 3, 30, 0, 0),
                            ConcertStart = new DateTime(2020, 7, 26, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("9c8bc32e-3239-45a2-a549-bba824deb663")
                        });
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ae18ad6-9809-4b19-be41-94aa4ff622f8"),
                            Country = "Slovakia",
                            Email = "xspavo00@vutrb.cz",
                            LoginId = new Guid("a2347ca2-4a12-46f6-9013-3596b07c63ed"),
                            Name = "David",
                            Role = 0,
                            Surname = "Spavor"
                        },
                        new
                        {
                            Id = new Guid("e3681bb8-1e7f-4e4f-8abe-58dbd211d6d1"),
                            City = "Bratislava",
                            Country = "Slovakia",
                            Email = "trdielko@hotmail.sk",
                            LoginId = new Guid("f7e5a131-c097-47fc-8900-65c51819ecee"),
                            Name = "Barbora",
                            Psc = "03855",
                            Role = 3,
                            Street = "Vajnorska",
                            Surname = "Bakosova"
                        });
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.FestivalInterpretEntity", b =>
                {
                    b.HasOne("FestivalProject.DAL.Entities.FestivalEntity", "Festival")
                        .WithMany("FestivalInterpret")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FestivalProject.DAL.Entities.InterpretEntity", "Interpret")
                        .WithMany("FestivalInterpret")
                        .HasForeignKey("InterpretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.LoginEntity", b =>
                {
                    b.HasOne("FestivalProject.DAL.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.MemberEntity", b =>
                {
                    b.HasOne("FestivalProject.DAL.Entities.InterpretEntity", null)
                        .WithMany("MemberList")
                        .HasForeignKey("InterpretEntityId");
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.ReservationEntity", b =>
                {
                    b.HasOne("FestivalProject.DAL.Entities.FestivalEntity", "Festival")
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FestivalProject.DAL.Entities.UserEntity", "User")
                        .WithMany("ReservationList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.StageEntity", b =>
                {
                    b.HasOne("FestivalProject.DAL.Entities.FestivalEntity", null)
                        .WithMany("StageList")
                        .HasForeignKey("FestivalEntityId");
                });

            modelBuilder.Entity("FestivalProject.DAL.Entities.StageInterpretEntity", b =>
                {
                    b.HasOne("FestivalProject.DAL.Entities.InterpretEntity", "Interpret")
                        .WithMany("StageInterpret")
                        .HasForeignKey("InterpretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FestivalProject.DAL.Entities.StageEntity", "Stage")
                        .WithMany("StageInterpret")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
